technology:
  - name: "TechCrunch"
    url: "https://techcrunch.com/feed/"
    category: "tech"

  - name: "The Verge"
    url: "https://www.theverge.com/rss/index.xml"
    category: "tech"

  - name: "Ars Technica"
    url: "https://feeds.arstechnica.com/arstechnica/index"
    category: "tech"

  - name: "Hacker News"
    url: "https://hnrss.org/frontpage"
    category: "tech"

  - name: "MIT Technology Review"
    url: "https://www.technologyreview.com/feed/"
    category: "tech"

  - name: "Wired"
    url: "https://www.wired.com/feed/rss"
    category: "tech"

investment:
  - name: "Bloomberg Markets"
    url: "https://feeds.bloomberg.com/markets/news.rss"
    category: "investment"

  - name: "Reuters Business"
    url: "https://www.reutersagency.com/feed/?taxonomy=best-topics&post_type=best"
    category: "investment"

  - name: "Financial Times"
    url: "https://www.ft.com/?format=rss"
    category: "investment"

  - name: "MarketWatch"
    url: "https://feeds.content.dowjones.io/public/rss/mw_topstories"
    category: "investment"

  - name: "Seeking Alpha"
    url: "https://seekingalpha.com/feed.xml"
    category: "investment"

  - name: "Yahoo Finance"
    url: "https://finance.yahoo.com/news/rssindex"
    category: "investment"

# Subtopics for filtering (optional)
subtopics:
  tech:
    - "artificial intelligence"
    - "machine learning"
    - "cloud computing"
    - "cybersecurity"
    - "cryptocurrency"
    - "blockchain"
    - "startups"
    - "venture capital"
    - "software"
    - "hardware"
    - "mobile"
    - "web development"

  investment:
    - "stock market"
    - "IPO"
    - "merger"
    - "acquisition"
    - "earnings"
    - "cryptocurrency"
    - "forex"
    - "commodities"
    - "bonds"
    - "fed"
    - "interest rates"
    - "inflation"
